### ISSUE TITLE
How-to?

### ISSUE THREAD

**Issue by djmtype** [KLicheR/wp-acf-unique_id#1]
The unique IDs have been generated for each of my repeaters, but how do I call a specific one by ID into my WP template? Please give an example.

**Comment by KLicheR** [comment]
Hi!
It's been a while since I used this plugin but as I remembered it, by activating it, you'll have access to a new type of field in ACF called "Unique ID".

Create one of those field within your repeater field and give it a name like any other field.

To access it's value within the template, you'll just have to fetch it like for any other field within your repeater group of fields by calling it by it's name.

Hope it helped!
